import os
import re
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.oxml.xmlchemy import OxmlElement

def add_fade_transition(slide):
    """Injects a fade transition into the slide's XML"""
    transition = OxmlElement('p:transition')
    fade = OxmlElement('p:fade')
    transition.append(fade)
    
    # p:cSld is always the first child in a valid p:sld element
    cSld = slide.element.xpath('./p:cSld')
    if cSld:
        cSld[0].addnext(transition)

def apply_background(slide):
    """Applies a sleek dark background to the slide"""
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(30, 34, 42)  # Dark sleek gray-blue

def create_presentation(parameters: dict, player=None) -> str:
    """
    Creates a highly detailed, professional PowerPoint presentation.
    """
    topic = parameters.get("topic", "Presentation")
    slides_data = parameters.get("slides", [])
    
    if not slides_data:
        return "Error: No slides provided to create presentation."
        
    if player:
        player.write_log(f"SYS: Creating presentation on '{topic}' with {len(slides_data)} slides...")

    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    apply_background(slide)
    add_fade_transition(slide)
    
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = topic
    if title.text_frame.paragraphs:
        title.text_frame.paragraphs[0].font.bold = True
        title.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 215, 0) # Gold
    
    subtitle.text = "Generated by Jarvis AI"
    if subtitle.text_frame.paragraphs:
        subtitle.text_frame.paragraphs[0].font.color.rgb = RGBColor(200, 200, 200)

    # Content slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_data in slides_data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        apply_background(slide)
        add_fade_transition(slide)
        
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data.get("title", "Untitled Slide")
        if title_shape.text_frame.paragraphs:
            title_shape.text_frame.paragraphs[0].font.bold = True
            title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
        
        tf = body_shape.text_frame
        bullets = slide_data.get("bullets", [])
        
        for i, bullet in enumerate(bullets):
            if i == 0:
                tf.text = bullet
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 0
            
            p.font.size = Pt(20)
            p.font.color.rgb = RGBColor(230, 230, 230)

    target_dir = parameters.get("directory")
    if not target_dir or not os.path.isdir(target_dir):
        target_dir = os.getcwd()

    safe_topic = re.sub(r'[\\/*?:"<>|]', "", topic[:30]).strip()
    filename = f"{safe_topic.replace(' ', '_')}.pptx"
    if not filename.strip('.pptx'):
        filename = "Presentation.pptx"

    save_path = os.path.join(target_dir, filename)
    
    try:
        prs.save(save_path)
        if player:
            player.write_log(f"SYS: Presentation saved to {save_path}")
        
        # Open it
        try:
            os.startfile(save_path)
        except Exception as open_err:
            if player:
                player.write_log(f"SYS: Could not automatically open presentation: {open_err}")
        
        return f"Presentation successfully created and saved to {save_path}."
    except Exception as e:
        return f"Error saving presentation: {e}"
